### ISSUE TITLE
CSS3 drop-shadow filter auto-magically includes pseudo elements

### ISSUE THREAD

**Issue by bookcasey** [hojberg/cssarrowplease#37]
`box-shadow: 0 1px 4px rgba(0, 0, 0, 0.3);` becomes `filter: drop-shadow(0 1px 4px rgba(0, 0, 0, 0.3));`

The glorious arrow now casts a shadow!

![Screen Shot 2012-12-23 at 12 28 24 AM](https://f.cloud.github.com/assets/1432129/28758/9016857c-4cc2-11e2-89df-1e2fed68bf6f.png)

Support is webkit only at this point, but I think that a little progressive enhancement couldn't hurt, either way I think it's a technique that is relevant to the interests of those using this tool.

**Comment by TomasHubelbauer** [comment]
Was this removed or ever released? As far as I can see, the application does not append this CSS rule. It seems to work very well if added manually, though.
