### ISSUE TITLE
Feature Request: rgba as background colour in option.

### ISSUE THREAD

**Issue by QuantumInformation** [hojberg/cssarrowplease#54]
Would love to see this! Solid colours are nice but would be great to have the arrows being able to be transparent.

ie in this use case:

![image](https://cloud.githubusercontent.com/assets/216566/21073403/e43c73ae-bed4-11e6-90de-c3e2207bb88a.png)

Also I am not quite sure what the purpose of the changing border-colour values if their opacity is 0.

![image](https://cloud.githubusercontent.com/assets/216566/21073398/d6827664-bed4-11e6-8957-282d25d45874.png)

**Comment by hojberg** [comment]
Yeah this sounds like a good idea.
I dont actually remember why the 0 opacity, it's been so long since i've worked on this.
I'll have a look this week.

**Comment by QuantumInformation** [comment]
I think the 0 just hides 3/4 of the border then the top-colour overrides. Actually I tried to change the settings but couldn't get alpha to work on the arrow at all.

**Comment by hojberg** [comment]
@QuantumInformation yep, but could be accomplished by just `transparent`. Sucks that alpha doesn't work :( I vaguely remember that now as well.

**Comment by QuantumInformation** [comment]
Sorry what do you mean by transparent?

**Comment by hojberg** [comment]
@QuantumInformation the "color" `transparent` can be used for backgrounds and borders

**Comment by QuantumInformation** [comment]
I tried transparent but it didn't work:

![image](https://cloud.githubusercontent.com/assets/216566/21955967/9643e0e2-da6d-11e6-8a38-bdcf3d8aa69b.png)

maybe this? 
http://stackoverflow.com/questions/8875968/pure-css-triangle-with-semi-transparent-border-possible
http://stackoverflow.com/questions/23758922/transparent-arrow-triangle
